server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: samille1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        jdbc:
          lob:
            non-contextual-creation: true